# Generated by Django 5.1.4 on 2025-01-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_marks_alter_student_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
