# Generated by Django 5.1.5 on 2025-01-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_marks'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marks',
            constraint=models.UniqueConstraint(fields=('student',), name='unique_student_marks'),
        ),
    ]
